version: 0.1.0-{build}
image:
- Visual Studio 2019
- Ubuntu
install:
- cmd: pip install conan
- cmd: git submodule update --init --recursive
- sh: pip3 install conan --user
- sh: git submodule update --init --recursive
build_script:  
- cmd: .\build.cmd
- sh: sh build.sh
artifacts:
- path: out/bin
  name: ncc