version: 0.1.0-{build}
image:
- Visual Studio 2019
- Ubuntu
install:
- cmd: pip install conan
- sh: pip install conan --user
build_script:  
- cmd: .\build.cmd
- sh: ./build.sh
artifacts:
- path: out/bin
  name: ncc