# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    windows:
      imageName: 'win2019'

pool:
  vmImage: $(imageName)

steps:
- checkout: self
  submodules: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6' 
    addToPath: true 
    architecture: 'x64'

- script: pip install conan
  displayName: 'Install Conan'

- script: |
    mkdir out && cd out
    sudo update-alternatives --set gcc /usr/bin/gcc-8
    cmake .. -DNNCASE_TARGET=k210 -DCMAKE_BUILD_TYPE=Release
    make -j
    strip bin/ncc
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: 'Build'

- script: |
    md out && cd out
    cmake .. -G "Visual Studio 16 2019" -A x64 -DNNCASE_TARGET=k210 -DCMAKE_BUILD_TYPE=Release
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Build'

- task: MSBuild@1
  inputs:
    solution: 'out/nncase.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Release'
    msbuildArguments: '-m'

- publish: out/bin
  artifact: ncc_linux_x64
  condition: eq( variables['Agent.OS'], 'Linux' )

- publish: out/bin
  artifact: ncc_win_x64
  condition: eq( variables['Agent.OS'], 'Windows_NT' )