# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
  submodules: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6' 
    addToPath: true 
    architecture: 'x64'

- script: pip install conan
  displayName: 'Install Conan'

- script: |
    md out && cd out
    cmake .. -G "Visual Studio 16 2019" -A x64 -DNNCASE_TARGET=k210 -DCMAKE_BUILD_TYPE=Release
  displayName: 'Build'

- task: MSBuild@1
  inputs:
    solution: 'nncase.sln'
    msbuildArchitecture: 'x64'
    configuration: 'Release'
    msbuildArguments: '-m'